# Generated by Django 4.2.10 on 2024-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=200)),
                ('order_position', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField()),
                ('order_email', models.CharField(max_length=200)),
            ],
        ),
    ]
